services:
  postgres:
    image: postgres:17-alpine
    container_name: psgr
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dbnet
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    links:
      - "postgres:db"
    networks:
      - dbnet
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    depends_on:
      - postgres

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - dbnet

  web:
    build: .
    image: school
    container_name: school
    restart: always
    # command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: /entrypoint_web.sh
    env_file:
      - ./.env
    networks:
      - dbnet
    working_dir: /app # Указание рабочей директории
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  celery:
    build: .
    image: selery
    container_name: selery
    # command: bash -c "python manage.py migrate && celery -A config worker --loglevel=info"
    command: /entrypoint_selery.sh
    working_dir: /app # Указание рабочей директории
    env_file:
      - ./.env
    networks:
      - dbnet
    volumes:
      - .:/app # Монтируем всю текущую директорию в контейнер, потому что "selery" нужна директория "config".
    depends_on:
      - postgres
      - redis

networks:
  dbnet:
    driver: bridge

volumes:
  postgres-data:
  static_volume:
